/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface.sub_user_interface;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.jar.JarEntry;

import javax.swing.JOptionPane;

import connect_to_database.KoneksiDatabase;

import user_interface.FormMendataBarang;

/**
 *
 * @author Gede Rico Wijaya - 2005551091
 */
public class SubMenuTambahSatuan extends javax.swing.JFrame {

    /**
     * Creates new form SubMenuTambahSatuan
     */
    public SubMenuTambahSatuan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NamaSatuan = new javax.swing.JTextField();
        Tambah_Label = new javax.swing.JLabel();
        Hapus_Label = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(188, 127, 108));
        jPanel1.setLayout(null);

        NamaSatuan.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 24)); // NOI18N
        NamaSatuan.setText("Nama Satuan");
        NamaSatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NamaSatuanMouseClicked(evt);
            }
        });
        jPanel1.add(NamaSatuan);
        NamaSatuan.setBounds(20, 110, 280, 70);

        Tambah_Label
                .setIcon(new javax.swing.ImageIcon("/Users/macos/NetBeansProjects/GeneratedReportPDF/icon/Tambah.png")); // NOI18N
        Tambah_Label.setText("jLabel1");
        Tambah_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tambah_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tambah_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(Tambah_Label);
        Tambah_Label.setBounds(20, 240, 140, 80);

        Hapus_Label
                .setIcon(new javax.swing.ImageIcon("/Users/macos/NetBeansProjects/GeneratedReportPDF/icon/Hapus.png")); // NOI18N
        Hapus_Label.setText("jLabel1");
        Hapus_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hapus_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hapus_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(Hapus_Label);
        Hapus_Label.setBounds(160, 240, 140, 80);

        Background.setIcon(new javax.swing.ImageIcon(
                "/Users/macos/NetBeansProjects/GeneratedReportPDF/icon/SubMenuCatatSatuan.png")); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, -20, 320, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 320, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaSatuanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NamaSatuanMouseClicked
        NamaSatuan.setText("");
    }// GEN-LAST:event_NamaSatuanMouseClicked

    public boolean cekTextField() {
        String Satuan = NamaSatuan.getText();

        // pengecekan TextField
        if (Satuan.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ketik Nama Kategori!", "Field Kosong", 2);
            return false;
        } else {
            return true;
        }
    }

    public boolean CekNamaSatuan(String SatuanBaru) {
        PreparedStatement StatementQuery;
        ResultSet HasilQuery;

        boolean NamaSatuan_Terdaftar = false;

        // query yang akan dijalankan pada database
        String query = "SELECT * FROM tb_kategori WHERE kode_kategori = ?";

        // pengecekan Nama Satuan
        try {
            StatementQuery = KoneksiDatabase.getConnection().prepareStatement(query);
            StatementQuery.setString(1, SatuanBaru);
            HasilQuery = StatementQuery.executeQuery();

            if (HasilQuery.next()) {
                NamaSatuan_Terdaftar = true;
                JOptionPane.showMessageDialog(null,
                        "Kategori Sudah Terdaftar, Silahkan Pilih Nama Kategori yang lain !", "Gagal terdaftar", 2);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Query Gagal", 2);
        }
        return NamaSatuan_Terdaftar;
    }

    private void Tambah_LabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Tambah_LabelMouseClicked
        PreparedStatement StatementQuery;
        String SatuanBaru = NamaSatuan.getText();
        if (cekTextField()) {
            if (!CekNamaSatuan(SatuanBaru)) {
                try {
                    String TambahSatuan = "INSERT INTO tb_satuan VALUES (NULL, ? , 'ACTIVE')";
                    StatementQuery = KoneksiDatabase.getConnection().prepareStatement(TambahSatuan);
                    StatementQuery.setString(1, SatuanBaru);
                    try {
                        if (StatementQuery.executeUpdate() != 0) {
                            JOptionPane.showMessageDialog(null, "Satuan Terdaftarkan");
                        } else {
                            JOptionPane.showMessageDialog(null, "Satuan Tidak Terhapus");
                        }
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.toString(), "Query Gagal", 2);
                }
            } else if (CekNamaSatuan(SatuanBaru) == true) {
                try {
                    String TambahSatuan = "UPDATE tb_satuan SET status = 'ACTIVE' WHERE satuan = ?";
                    StatementQuery = KoneksiDatabase.getConnection().prepareStatement(TambahSatuan);
                    StatementQuery.setString(1, SatuanBaru);
                    try {
                        if (StatementQuery.executeUpdate() != 0) {
                            JOptionPane.showMessageDialog(null, "Satuan Terdaftarkan");
                        } else {
                            JOptionPane.showMessageDialog(null, "Satuan Tidak Terhapus");
                        }
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
            FormMendataBarang mendataBarang = new FormMendataBarang();
            mendataBarang.getDataForSatuanComboBox();
        }
    }// GEN-LAST:event_Tambah_LabelMouseClicked

    private void Hapus_LabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Hapus_LabelMouseClicked
        PreparedStatement StatementQuery;
        String SatuanLama = NamaSatuan.getText();
        try {
            String HapusKategori = "UPDATE tb_satuan SET status = 'NOT ACTIVE' WHERE satuan = ?";
            StatementQuery = KoneksiDatabase.getConnection().prepareStatement(HapusKategori);
            StatementQuery.setString(1, SatuanLama);
            try {
                if (StatementQuery.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "Kategori Terhapuskan");
                } else {
                    JOptionPane.showMessageDialog(null, "Kategori Terhapus");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString(), "Query Gagal", 2);
        }
    }// GEN-LAST:event_Hapus_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMenuTambahSatuan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMenuTambahSatuan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMenuTambahSatuan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMenuTambahSatuan.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMenuTambahSatuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Hapus_Label;
    private javax.swing.JTextField NamaSatuan;
    private javax.swing.JLabel Tambah_Label;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
