/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import connect_to_database.KoneksiDatabase;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macos
 */
public class FormRiwayatPendataan extends javax.swing.JFrame {

    /**
     * Creates new form FormRiwayatPencatatan
     */
    public FormRiwayatPendataan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Check_Label = new javax.swing.JLabel();
        Create_Label = new javax.swing.JLabel();
        Label_Tanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSTOK = new javax.swing.JTable();
        Kembali_Label = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jDateChooser1.setBackground(new java.awt.Color(214, 236, 243));
        jDateChooser1.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 12)); // NOI18N
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(70, 200, 260, 50);

        Check_Label.setIcon(new javax.swing.ImageIcon("/Users/macos/NetBeansProjects/GeneratedReportPDF/icon/Check_Kecil.png")); // NOI18N
        Check_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Check_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Check_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(Check_Label);
        Check_Label.setBounds(120, 320, 140, 80);

        Create_Label.setIcon(new javax.swing.ImageIcon("/Users/macos/NetBeansProjects/GeneratedReportPDF/icon/Create_Kecil.png")); // NOI18N
        Create_Label.setText("Create");
        Create_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Create_Label);
        Create_Label.setBounds(120, 440, 150, 80);

        Label_Tanggal.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 14)); // NOI18N
        Label_Tanggal.setText("Tanggal Yang Dicari");
        jPanel1.add(Label_Tanggal);
        Label_Tanggal.setBounds(70, 180, 150, 22);

        TabelSTOK.setBackground(new java.awt.Color(214, 236, 243));
        TabelSTOK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Display", "Display Akhir (penjualan)", "Gudang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelSTOK);
        if (TabelSTOK.getColumnModel().getColumnCount() > 0) {
            TabelSTOK.getColumnModel().getColumn(0).setResizable(false);
            TabelSTOK.getColumnModel().getColumn(1).setResizable(false);
            TabelSTOK.getColumnModel().getColumn(2).setResizable(false);
            TabelSTOK.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 150, 630, 420);

        Kembali_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kembali_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kembali_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(Kembali_Label);
        Kembali_Label.setBounds(10, 590, 90, 70);

        Background.setIcon(new javax.swing.ImageIcon("/Users/macos/NetBeansProjects/GeneratedReportPDF/icon/RiwayatPencatatan.png")); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(10, -10, 1060, 680);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 1060, 680);

        setSize(new java.awt.Dimension(1071, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Kembali_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kembali_LabelMouseClicked
        FormHome beranda = new FormHome();
        beranda.show();
        this.dispose();
    }//GEN-LAST:event_Kembali_LabelMouseClicked

    private void Check_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Check_LabelMouseClicked
        // TODO add your handling code here:
          // variabel untuk mengekseksusi query
        PreparedStatement Statement;
        // sebuah cursor untuk baris dari tabel tersebut
        ResultSet HasilExecuteQuery;
        
        SimpleDateFormat format_tanggal = new SimpleDateFormat("dd-MM-yyyy");
        String d1  = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();


        DefaultTableModel Tabel = (DefaultTableModel) TabelSTOK.getModel();
        Tabel.setRowCount(0);

        try {
            // query untuk mengecek password dan username sudah terdatftar
            String query = "SELECT tb_barang.nama_barang, tb_histori_pendataan.stok_display, tb_histori_pendataan.stok_masuk_display, tb_histori_pendataan.stok_gudang FROM tb_histori_pendataan JOIN tb_barang ON tb_histori_pendataan.id_barang = tb_barang. id_barang WHERE tanggal = ? "  ;
            Statement = KoneksiDatabase.getConnection().prepareStatement(query);
            Statement.setString(1, query);
            HasilExecuteQuery = Statement.executeQuery();
            while (HasilExecuteQuery.next()) {
                String NamaBarang = String.valueOf(HasilExecuteQuery.getString("nama_barang"));
                String StokAwal = String.valueOf(HasilExecuteQuery.getString("stok_display"));
                String StokIn = String.valueOf(HasilExecuteQuery.getString("stok_masuk_display"));
                String StokGudang = String.valueOf(HasilExecuteQuery.getString("stok_gudang"));

                String data[] = { NamaBarang, StokAwal, StokIn, StokGudang };
                Tabel.addRow(data);
            }
        } catch (Exception e) {
            System.err.print(e);
        }
    }//GEN-LAST:event_Check_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRiwayatPendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRiwayatPendataan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Check_Label;
    private javax.swing.JLabel Create_Label;
    private javax.swing.JLabel Kembali_Label;
    private javax.swing.JLabel Label_Tanggal;
    private javax.swing.JTable TabelSTOK;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
